In [307]:
#Setting up
import pandas as pd
import csv, matplotlib.pyplot as plt
import os
os.system('clear')

#Opening the files
unemployment = pd.read_csv('unemploymentDataByStates.csv')
population = pd.read_csv('populationDataset.csv')
gdpData = pd.read_csv('GDPData.csv')

In [308]:
year13 = [col for col in unemployment.columns if '13' in col]
unemployment['UER2013'] = unemployment[year13].sum(axis=1)
unemployment['UER2013'] = unemployment['UER2013']/12

year14 = [col for col in unemployment.columns if '14' in col]
unemployment['UER2014'] = unemployment[year14].sum(axis=1)
unemployment['UER2014'] = unemployment['UER2014']/12

year15 = [col for col in unemployment.columns if '15' in col]
unemployment['UER2015'] = unemployment[year15].sum(axis=1)
unemployment['UER2015'] = unemployment['UER2015']/12

year16 = [col for col in unemployment.columns if '16' in col]
unemployment['UER2016'] = unemployment[year16].sum(axis=1)
unemployment['UER2016'] = unemployment['UER2016']/12

year17 = [col for col in unemployment.columns if '17' in col]
unemployment['UER2017'] = unemployment[year17].sum(axis=1)
unemployment['UER2017'] = unemployment['UER2017']/12

year18 = [col for col in unemployment.columns if '18' in col]
unemployment['UER2018'] = unemployment[year18].sum(axis=1)
unemployment['UER2018'] = unemployment['UER2018']/12

year19 = [col for col in unemployment.columns if '19' in col]
unemployment['UER2019'] = unemployment[year19].sum(axis=1)
unemployment['UER2019'] = unemployment['UER2019']/12

unemployment.reset_index(inplace = True, drop = False)
unemployment.drop(unemployment.columns.difference(['State','UER2013','UER2014','UER2015','UER2016','UER2017','UER2018','UER2019']), 1, inplace = True)

#unemployment

/var/folders/6t/5n6hzyfd7bxc1pxzzzxd788w0000gn/T/ipykernel_80274/847704015.py:30: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  unemployment.drop(unemployment.columns.difference(['State','UER2013','UER2014','UER2015','UER2016','UER2017','UER2018','UER2019']), 1, inplace = True)

In [309]:
year13 = [col for col in gdpData.columns if '14' in col]
gdpData['GDP2013'] = gdpData[year13].sum(axis=1)
gdpData['GDP2013'] = gdpData['GDP2013']/12

year14 = [col for col in gdpData.columns if '14' in col]
gdpData['GDP2014'] = gdpData[year14].sum(axis=1)
gdpData['GDP2014'] = gdpData['GDP2014']/12

year15 = [col for col in gdpData.columns if '15' in col]
gdpData['GDP2015'] = gdpData[year15].sum(axis=1)
gdpData['GDP2015'] = gdpData['GDP2015']/12

year16 = [col for col in gdpData.columns if '16' in col]
gdpData['GDP2016'] = gdpData[year16].sum(axis=1)
gdpData['GDP2016'] = gdpData['GDP2016']/12

year17 = [col for col in gdpData.columns if '17' in col]
gdpData['GDP2017'] = gdpData[year17].sum(axis=1)
gdpData['GDP2017'] = gdpData['GDP2017']/12

year18 = [col for col in gdpData.columns if '18' in col]
gdpData['GDP2018'] = gdpData[year18].sum(axis=1)
gdpData['GDP2018'] = gdpData['GDP2018']/12

year19 = [col for col in gdpData.columns if '19' in col]
gdpData['GDP2019'] = gdpData[year19].sum(axis=1)
gdpData['GDP2019'] = gdpData['GDP2019']/12

gdpData.reset_index(inplace = True, drop = False)
gdpData.drop(gdpData.columns.difference(['GeoName','GDP2013','GDP2014','GDP2015','GDP2016','GDP2017','GDP2018','GDP2019']), 1, inplace = True)

#gdpData

/var/folders/6t/5n6hzyfd7bxc1pxzzzxd788w0000gn/T/ipykernel_80274/3837021398.py:30: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  gdpData.drop(gdpData.columns.difference(['GeoName','GDP2013','GDP2014','GDP2015','GDP2016','GDP2017','GDP2018','GDP2019']), 1, inplace = True)

In [310]:
#Delete columns
del population['SUMLEV']
del population['REGION']
del population['DIVISION']
del population['STATE']
del population['ESTIMATESBASE2010']
del population['NPOPCHG_2010']
del population['NPOPCHG_2011']
del population['NPOPCHG_2012']
del population['NPOPCHG_2013']
del population['NPOPCHG_2014']
del population['NPOPCHG_2015']
del population['NPOPCHG_2016']
del population['NPOPCHG_2017']
del population['NPOPCHG_2018']
del population['NPOPCHG_2019']
del population['PPOPCHG_2010']
del population['PPOPCHG_2011']
del population['PPOPCHG_2012']
del population['PPOPCHG_2013']
del population['PPOPCHG_2014']
del population['PPOPCHG_2015']
del population['PPOPCHG_2016']
del population['PPOPCHG_2017']
del population['PPOPCHG_2018']
del population['PPOPCHG_2019']
del population['NRANK_ESTBASE2010']
del population['NRANK_POPEST2010']
del population['NRANK_POPEST2011']
del population['NRANK_POPEST2012']
del population['NRANK_POPEST2013']
del population['NRANK_POPEST2014']
del population['NRANK_POPEST2015']
del population['NRANK_POPEST2016']
del population['NRANK_POPEST2017']
del population['NRANK_POPEST2018']
del population['NRANK_POPEST2019']
del population['NRANK_NPCHG2010']
del population['NRANK_NPCHG2011']
del population['NRANK_NPCHG2012']
del population['NRANK_NPCHG2013']
del population['NRANK_NPCHG2014']
del population['NRANK_NPCHG2015']
del population['NRANK_NPCHG2016']
del population['NRANK_NPCHG2017']
del population['NRANK_NPCHG2018']
del population['NRANK_NPCHG2019']
del population['NRANK_PPCHG2010']
del population['NRANK_PPCHG2011']
del population['NRANK_PPCHG2012']
del population['NRANK_PPCHG2013']
del population['NRANK_PPCHG2014']
del population['NRANK_PPCHG2015']
del population['NRANK_PPCHG2016']
del population['NRANK_PPCHG2017']
del population['NRANK_PPCHG2018']
del population['NRANK_PPCHG2019']

population.drop([0,1,2,3,4], axis = 0, inplace=True)
population.reset_index(inplace = True, drop = True)
del population['POPESTIMATE2010']
del population['POPESTIMATE2011']
del population['POPESTIMATE2012']

In [311]:
unemployment.set_index('State',inplace=True)
#unemployment = unemployment.dropna()
#unemployment.drop([0],axis=0,inplace=True)
unemployment = unemployment.transpose()
unemployment = unemployment.reset_index(drop=False,inplace=False)
unemployment

State,index,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,UER2013,7.325000,6.991667,7.816667,7.041667,9.033333,6.750000,7.950000,6.608333,8.433333,...,7.725000,6.300000,4.208333,4.416667,5.550000,6.633333,6.716667,6.641667,4.733333,14.233333
1,UER2014,6.733333,6.741667,6.791667,5.900000,7.566667,4.983333,6.616667,5.608333,7.708333,...,6.600000,5.191667,3.633333,3.991667,5.116667,5.925000,6.500000,5.350000,4.341667,13.833333
2,UER2015,6.125000,6.275000,6.075000,4.950000,6.225000,3.741667,5.616667,4.791667,6.916667,...,5.566667,4.483333,3.508333,3.533333,4.366667,5.433333,6.583333,4.425000,4.208333,12.058333
3,UER2016,5.908333,6.600000,5.483333,3.983333,5.516667,3.133333,4.866667,4.525000,6.233333,...,4.758333,4.650000,3.350000,3.125000,4.000000,5.225000,6.091667,3.908333,5.333333,11.750000
4,UER2017,4.508333,6.508333,4.975000,3.741667,4.833333,2.608333,4.416667,4.466667,6.100000,...,3.750000,4.341667,3.166667,3.008333,3.666667,4.641667,5.208333,3.258333,4.325000,10.908333
5,UER2018,3.916667,5.966667,4.808333,3.633333,4.258333,3.008333,3.933333,3.775000,5.658333,...,3.500000,3.900000,2.925000,2.616667,2.950000,4.450000,5.183333,2.975000,4.050000,9.175000
6,UER2019,3.158333,5.475000,4.858333,3.466667,4.116667,2.600000,3.533333,3.700000,5.341667,...,3.400000,3.516667,2.583333,2.325000,2.750000,4.300000,4.900000,3.183333,3.750000,8.291667

In [312]:
# dataframe = pd.merge(unemployment,gdpData,left_on='State',right_on='GeoName')
# dataframe = pd.merge(dataframe,population,left_on='State',right_on='NAME')
# del dataframe['GeoName']
# del dataframe['NAME']
# #dataframe
# dataframe.reset_index(drop=False,inplace=False)
# dataframe2 = dataframe.transpose()
# #print(dataframe2)